[workspace]
resolver = "2"

members = [
  "spike-rs",
  "implementations/native_c",
  # "implementations/memory",
  # "hdf5-rs",
  # "implementations/spike-h5",
  # "tests",
  # "pycode-rs",
  # "mc_explorer",
]
