[package]
name = "spike-rs"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
name = "spyke_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
numpy = "*"

[build-dependencies]
bindgen = "*"
