[package]
name = "code-rs"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
cstr = "0.2.11"

[build-dependencies]
bindgen = "0.69.2"
pkg-config = "0.3.29"
cc-args = { version = "0.2.0", features = ["bindgen", "pkg-config"] }
