[workspace]
members = [ "crates/spike-rs", ]

[package]
name = "pycode-rs"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[lib]
name = "pycode"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "*"
spike_rs = { path = "./crates/spike-rs"}

[build-dependencies]
cmake = "*"
bindgen = "*"

