[package]
name = "mc_explorer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hdf5-rs = { path = "../hdf5-rs" }
spike-rs = { path = "../spike-rs" }
