[package]
name = "pycode-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "pycode_rs"
crate-type = ["cdylib"]

[dependencies]
spike-rs = { path = "../spike-rs" }
mc_explorer = { path = "../mc_explorer"}
pyo3 = { version = "0.19.0", features = ["extension-module"] }
