[package]
name = "pycode-rs"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib"]
bench = false

[dependencies]
pyo3 = "*"

[build-dependencies]
cmake = "*"
bindgen = "*"
git2 = "*"
