[package]
name = "native_c"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib"]
bench = false

[dependencies]
spike-rs = { path = "../../spike-rs" }
pyo3 = "*"

[build-dependencies]
cmake = "*"
bindgen = "*"
git2 = "*"
